[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@chainlink/=lib/chainlink-brownie-contracts/contracts/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@prb/math/=lib/prb-math/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]